# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox"
  config.vm.box = "archlinux/archlinux"
  config.vm.disk :disk, size: "50GB", primary: true
  config.vm.network "public_network"
  config.vm.synced_folder "./synced-folder", "/vagrant"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "16384"
    vb.cpus = "8"
  end

end
