live_config_reload = true

# Colors (Nordic)
# https://github.com/alacritty/alacritty-theme/blob/master/themes/nordic.toml

[colors.primary]
background = '#242933'
foreground = '#BBBDAF'

[colors.normal]
black = '#191C1D'
red = '#BD6062'
green = '#A3D6A9'
yellow = '#F0DFAF'
blue = '#8FB4D8'
magenta = '#C7A9D9'
cyan = '#B6D7A8'
white = '#BDC5BD'

[colors.bright]
black = '#727C7C'
red = '#D18FAF'
green = '#B7CEB0'
yellow = '#BCBCBC'
blue = '#E0CF9F'
magenta = '#C7A9D9'
cyan = '#BBDA97'
white = '#BDC5BD'

[colors.selection]
text = '#000000'
background = '#F0DFAF'

[env]
WINIT_X11_SCALE_FACTOR = "1.16"

[font]
size = 9

[font.bold]
family = "FiraMonoNerdFontPropo"
style = "Bold"

[font.normal]
family = "FiraMonoNerdFontMono"
style = "Medium"
