
# Kanagawa Alacritty Colors
# https://github.com/rebelot/kanagawa.nvim/blob/master/extras/alacritty_kanagawa.yml

[[colors.indexed_colors]]
color = "0xffa066"
index = 16

[[colors.indexed_colors]]
color = "0xff5d62"
index = 17

[colors.bright]
black = "0x727169"
blue = "0x7fb4ca"
cyan = "0x7aa89f"
green = "0x98bb6c"
magenta = "0x938aa9"
red = "0xe82424"
white = "0xdcd7ba"
yellow = "0xe6c384"

[colors.normal]
black = "0x090618"
blue = "0x7e9cd8"
cyan = "0x6a9589"
green = "0x76946a"
magenta = "0x957fb8"
red = "0xc34043"
white = "0xc8c093"
yellow = "0xc0a36e"

[colors.primary]
background = "0x1f1f28"
foreground = "0xdcd7ba"

[colors.selection]
background = "0x2d4f67"
foreground = "0xc8c093"

[env]
WINIT_X11_SCALE_FACTOR = "1.16"

[font]
size = 9

[font.bold]
family = "FiraMonoNerdFontPropo"
style = "Bold"

[font.normal]
family = "FiraMonoNerdFontMono"
style = "Medium"

[general]
live_config_reload = true
