#!/bin/bash

PERSONALPROJ="$HOME/dev/personal/projects/"

function loopDir() {
	for dir in $(ls $PERSONALPROJ); do
		showGitInfo
	done
}

function showGitInfo() {
	if [[ -d "$PERSONALPROJ$dir/.git" ]]; then
		echo ""
		echo "========[${dir^^}]========"
		echo `git --git-dir $PERSONALPROJ$dir/.git log\
		 --oneline --date=relative --format=format:'[%ar] %s' --all --max-count=1}`
	fi
}

echo "######## FROM dev/personal/projects ########"

loopDir

# @TODO: find a way to put CONFS and GW in the loop

CONFS="/home/thassiov/confs/"
echo ""
echo "[CONFS] My configuration files"
echo `git --git-dir $CONFS.git log\
 --oneline --date=relative --format=format:'[%ar] %s' --all --max-count=1}`

echo ""
echo "######## FROM dev/moss ########"

GW="/home/thassiov/dev/moss/gw/"
echo "[GW] Graduwe API"
echo `git --git-dir $GW.git log\
 --oneline --date=relative --format=format:'[%ar] %s' --all --max-count=1}`

