#!/bin/bash

echo "######## FROM dev/personal/projects ########"

echo "[WIT] Write it!"
echo `git --git-dir /home/thassiov/dev/personal/projects/wit/.git log\
 --oneline --date=relative --format=format:'[%ar] %s' --all --max-count=1}`

echo ""
echo "[OYE] ZSH Theme"
echo `git --git-dir /home/thassiov/dev/personal/projects/oye/.git log\
 --oneline --date=relative --format=format:'[%ar] %s' --all --max-count=1}`

echo ""
echo "[DOIT] A task manager for programmers"
echo `git --git-dir /home/thassiov/dev/personal/projects/doit/.git log\
 --oneline --date=relative --format=format:'[%ar] %s' --all --max-count=1}`

echo ""
echo "[GOALS] My personal goals"
echo `git --git-dir /home/thassiov/dev/personal/projects/goals/.git log\
 --oneline --date=relative --format=format:'[%ar] %s' --all --max-count=1}`

echo ""
echo "[DTF] Task journal"
echo `git --git-dir /home/thassiov/dev/personal/projects/dtf/.git log\
 --oneline --date=relative --format=format:'[%ar] %s' --all --max-count=1}`

echo ""
echo "[THEKATA] Do katas everyday"
echo `git --git-dir /home/thassiov/dev/personal/projects/thekata/.git log\
 --oneline --date=relative --format=format:'[%ar] %s' --all --max-count=1}`

echo ""
echo "[CONFS] My configuration files"
echo `git --git-dir /home/thassiov/confs/.git log\
 --oneline --date=relative --format=format:'[%ar] %s' --all --max-count=1}`

echo ""
echo "######## FROM dev/moss ########"

echo "[GW] Graduwe API"
echo `git --git-dir /home/thassiov/dev/moss/gw/.git log\
 --oneline --date=relative --format=format:'[%ar] %s' --all --max-count=1}`
