#!/bin/bash

font="Fira Mono Medium-12"

dmenu_run -i -h 768 -w 1366 -q -l 1 -o .9 -p "                                     execute" -fn "$font" -nb "#000000" -nf "#bbbbbb" -sb "#000000" -sf "#377222"
