setxkbmap -model logitech_base -layout us
setxkbmap -option ctrl:swap_rwin_rctl
#setxkbmap -option caps:swapescape
#setxkbmap -option lv3:ralt_switch

# Possible options [localectl list-x11-keymap-options]
#Compose
#altwin
#altwin:alt_super_win
#altwin:alt_win
#altwin:ctrl_alt_win
#altwin:ctrl_win
#altwin:hyper_win
#altwin:left_meta_win
#altwin:menu
#altwin:menu_win
#altwin:meta_alt
#altwin:meta_win
#altwin:prtsc_rwin
#altwin:swap_alt_win
#altwin:swap_lalt_lwin
#apple:alupckeys
#caps
#caps:backspace
#caps:capslock
#caps:ctrl_modifier
#caps:escape
#caps:escape_shifted_capslock
#caps:hyper
#caps:internal
#caps:internal_nocancel
#caps:menu
#caps:none
#caps:numlock
#caps:shift
#caps:shift_nocancel
#caps:shiftlock
#caps:super
#caps:swapescape
#compat
#compose:102
#compose:102-altgr
#compose:caps
#compose:caps-altgr
#compose:lctrl
#compose:lctrl-altgr
#compose:lwin
#compose:lwin-altgr
#compose:menu
#compose:menu-altgr
#compose:paus
#compose:prsc
#compose:ralt
#compose:rctrl
#compose:rctrl-altgr
#compose:rwin
#compose:rwin-altgr
#compose:sclk
#ctrl
#ctrl:aa_ctrl
#ctrl:ac_ctrl
#ctrl:lctrl_meta
#ctrl:menu_rctrl
#ctrl:nocaps
#ctrl:rctrl_ralt
#ctrl:swap_lalt_lctl
#ctrl:swap_lalt_lctl_lwin
#ctrl:swap_lwin_lctl
#ctrl:swap_rwin_rctl
#ctrl:swapcaps
#ctrl:swapcaps_hyper
#currencysign
#esperanto
#esperanto:colemak
#esperanto:dvorak
#esperanto:qwerty
#eurosign:2
#eurosign:4
#eurosign:5
#eurosign:e
#grab:break_actions
#grab:debug
#grp
#grp:alt_caps_toggle
#grp:alt_shift_toggle
#grp:alt_space_toggle
#grp:alts_toggle
#grp:caps_switch
#grp:caps_toggle
#grp:ctrl_alt_toggle
#grp:ctrl_shift_toggle
#grp:ctrls_toggle
#grp:lalt_lshift_toggle
#grp:lalt_toggle
#grp:lctrl_lshift_toggle
#grp:lctrl_lwin_rctrl_menu
#grp:lctrl_lwin_toggle
#grp:lctrl_rctrl_switch
#grp:lctrl_toggle
#grp:lshift_toggle
#grp:lswitch
#grp:lwin_switch
#grp:lwin_toggle
#grp:menu_switch
#grp:menu_toggle
#grp:rctrl_rshift_toggle
#grp:rctrl_switch
#grp:rctrl_toggle
#grp:rshift_toggle
#grp:rwin_switch
#grp:rwin_toggle
#grp:sclk_toggle
#grp:shift_caps_switch
#grp:shift_caps_toggle
#grp:shifts_toggle
#grp:switch
#grp:toggle
#grp:win_menu_switch
#grp:win_space_toggle
#grp:win_switch
#grp_led
#grp_led:caps
#grp_led:num
#grp_led:scroll
#japan
#japan:hztg_escape
#japan:kana_lock
#japan:nicola_f_bs
#keypad
#keypad:atm
#keypad:future
#keypad:future_wang
#keypad:hex
#keypad:legacy
#keypad:legacy_wang
#keypad:oss
#keypad:oss_wang
#keypad:pointerkeys
#korean
#korean:ralt_hangul
#korean:ralt_hanja
#korean:rctrl_hangul
#korean:rctrl_hanja
#kpdl
#kpdl:comma
#kpdl:commaoss
#kpdl:dot
#kpdl:dotoss
#kpdl:dotoss_latin9
#kpdl:kposs
#kpdl:momayyezoss
#kpdl:semi
#lv3
#lv3:alt_switch
#lv3:bksl_switch
#lv3:bksl_switch_latch
#lv3:caps_switch
#lv3:caps_switch_latch
#lv3:enter_switch
#lv3:lalt_switch
#lv3:lsgt_switch
#lv3:lsgt_switch_latch
#lv3:lwin_switch
#lv3:menu_switch
#lv3:ralt_alt
#lv3:ralt_switch
#lv3:ralt_switch_multikey
#lv3:rwin_switch
#lv3:switch
#lv3:win_switch
#lv5
#lv5:lsgt_switch
#lv5:lsgt_switch_lock
#lv5:lsgt_switch_lock_cancel
#lv5:lwin_switch_lock
#lv5:ralt_switch
#lv5:ralt_switch_lock
#lv5:rwin_switch_lock
#misc:typo
#mod_led
#mod_led:compose
#nbsp
#nbsp:level2
#nbsp:level3
#nbsp:level3n
#nbsp:level3s
#nbsp:level4
#nbsp:level4n
#nbsp:level4nl
#nbsp:none
#nbsp:zwnj2
#nbsp:zwnj2nb3
#nbsp:zwnj2nb3nnb4
#nbsp:zwnj2nb3s
#nbsp:zwnj2nb3zwj4
#nbsp:zwnj2zwj3
#nbsp:zwnj2zwj3nb4
#nbsp:zwnj3zwj4
#numpad:mac
#numpad:microsoft
#numpad:pc
#numpad:shift3
#rupeesign:4
#shift:both_capslock
#shift:both_capslock_cancel
#shift:both_shiftlock
#shift:breaks_caps
#solaris
#solaris:sun_compat
#srvrkeys:none
#terminate
#terminate:ctrl_alt_bksp
