-- Treesitter
-- Advanced syntax highlighting and code parsing

return {
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    opts = {
      ensure_installed = {
        "bash",
        "c",
        "html",
        "lua",
        "markdown",
        "vim",
        "vimdoc",
        "cpp",
        "css",
        "cmake",
        "diff",
        "csv",
        "dockerfile",
        "git_config",
        "git_rebase",
        "gitcommit",
        "gitignore",
        "graphql",
        "hcl",
        "jsdoc",
        "json",
        "jsonc",
        "javascript",
        "luadoc",
        "passwd",
        "pem",
        "python",
        "rasi",
        "readline",
        "regex",
        "rust",
        "go",
        "sql",
        "ssh_config",
        "terraform",
        "toml",
        "tmux",
        "tsx",
        "xml",
      },
      auto_install = true,
      highlight = {
        enable = true,
        additional_vim_regex_highlighting = { "ruby" },
      },
      indent = { enable = false },
    },
    config = function(_, opts)
      require("nvim-treesitter.configs").setup(opts)
    end,
  },
}
